import '@radix-ui/themes/styles.css';
import './theme-config.css';
import {Theme} from '@radix-ui/themes';
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Navbar from "./NavBar";

const inter = Inter({
    subsets: ["latin"],
    variable: '--font-inter'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.variable}>
          <Theme
              accentColor="iris"
              grayColor="gray"
              panelBackground="translucent"
              scaling="100%"
              radius="medium"
              appearance="light"
          >
              <Navbar/>
              <main className="p-6">
                {children}
              </main>
          </Theme>
      </body>
    </html>
  );
}
